
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3307/test?characterEncoding=utf-8&useSSL=false
    tomcat:
      min-idle: 10 #最大等待连接数
      max-active: 50 #最大连接活动数
      max-wait: 10000 #最大连接等待毫秒数
      initial-size: 5 #连接池初始化连接数
#  redis:
#    host: 192.168.15.128
#    port: 6379
#    timeout: 10s
#    jedis:
#      pool:
#        max-active: 10
#        min-idle: 5
#        max-idle: 10
#        max-wait: 20s
#  cache:
#    type: redis #缓存类型
#    cache-names: redisCache   #缓存名称,多个用,分割
mybatis:
  mapper-locations: classpath:mapper/*-mapper.xml
  type-aliases-package: com.hou.groovy.bean.PO
logging:
  level:
    root: DEBUG    #配置日志级别
    org.springframework: DEBUG
    org.mybatis: DEBUG