spring:
  datasource:
    dynamic:
      hikari: # 整合hikari 设置全局参数,所有数据源默认一致
        connection-timeout: 20000
        max-pool-size: 12
        min-idle: 5
        idle-timeout: 300000
        pool-name: DatebookHikariCP
        max-lifetime: 1800000
      datasource:
        master: # 写
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        slave: # 读
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  typeEnumsPackage: com.hou.mybatisplus.user.enums # 配置扫描通用枚举

# 端点监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
