spring:
  redis:
    host: 192.168.15.128
    port: 6379
    timeout: 10s
    jedis:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
        max-wait: 20s
  cache:
    type: redis #缓存类型
    cache-names: redisCache   #缓存名称,多个用,分割
server:
  port: 8080
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.mybatis: DEBUG